export const recentClients = [
    {
        id: 1,
        img: "https://kirbyandtheforgottenland.nintendo.com/assets/images/characters/character-bandana.png",
        name: "Bandana Waddle Dee",
        email: "bwd@kirby.co.jp",
        number: "563-271-1291",
    },
    {
        id: 2,
        img: "https://kirbyandtheforgottenland.nintendo.com/assets/images/characters/character-elfilin-medium-up.png",
        name: "Elfilin",
        email: "elf@kirby.co.jp",
        number: "712-363-4109",
    },
    {
        id: 3,
        img: "https://www.giantbomb.com/a/uploads/square_small/15/150372/3256287-marx_small_ssbu.png",
        name: "Marx",
        email: "marx@kirby.co.jp",
        number: "436-723-9816",
    },
    {
        id: 4,
        img: "https://static.wikia.nocookie.net/kirby/images/0/0b/1543204521785.png/revision/latest?cb=20181229025645&path-prefix=en",
        name: "ChuChu",
        email: "chuchu@kirby.co.jp",
        number: "342-170-0010",
    },
    {
        id: 5,
        img: "https://cdn.wikirby.com/2/2c/KDL3_Nago_artwork.png",
        name: "Nago",
        email: "nago@kirby.co.jp",
        number: "135-266-0198",
    },
    {
        id: 6,
        img: "https://cdn.wikirby.com/9/9e/KDL3_Pitch_artwork.png",
        name: "Pitch",
        email: "pitch@kirby.co.jp",
        number: "641-215-5874",
    },
    {
        id: 7,
        img: "https://static.wikia.nocookie.net/kirby/images/a/a7/HnK_Pon.png/revision/latest?cb=20130823203929&path-prefix=en",
        name: "Pon",
        email: "pon@kirby.co.jp",
        number: "534-175-4441",
    },
];